### PR TITLE
Rework the README

### PR DESCRIPTION
**Pull request by Bengt**
I reworked the readme file to follow the user journey from finding this package via building, using and contributing back to it. I also added instructions for installing the buildtime prerequisites for easier reproduction.

### CODE REVIEW

**Comment by clbr** [comment]
Sorry, I disagree with the new order. More users will read it to find what it is than to find how to build it. Further, I will not endorse any particular distro; I will not accept Ubuntu-specific instructions.

**Comment by Bengt** [comment]
Thanks for resolving this quickly. I find your choice odd, though.

The first paragraph still describes hat RadeonTop is. So I do not see what you are on about.

No user can use it without building it first, so I think instructions for building should go first. That feels natural and makes to most sense as a user journey.

Another way to not endorse any particular distribution is to have instructions for all (major) ones. I added some for Ubuntu because that is what I use and can thus easily verify. Other users could contribute more instructions to improve the experience for the largest audience possible.

**Comment by clbr** [comment]
Many distros have radeontop packaged, including Ubuntu.

**Comment by Bengt** [comment]
In my case, the RadeonTop from Ubuntu's repositories did not support my GPU Vega 10 / RX Vega 64. That's why I came to this repository for instructions on building it myself and got greeted with instructions on how to use it, which I already was familiar with.

Maybe many users could be helped with instructions to install the package from their distro's repos before considering building from source?

**Comment by clbr** [comment]
Well, I think it would be repeating the obvious if the readme said "try
your distro's package", that's the default mode for users. apt-get
commands would again be distro-specific.

**Comment by Bengt** [comment]
It seems obvious to me that users of a random distro seeing the README for the first time, would like concrete recommendations on how to install the package on the their systems. I feel like we have some deeper disagreement here. My goal here is to make this awesome package as accessible as possible to as many people as possible. Can you support this goal?

**Pull request closed without merging**
