### PR TITLE
added navy flounder support

### PR DESCRIPTION
**Pull request by dr-br**

### CODE REVIEW

**Comment by clbr** [comment]
This doesn't match the order in the linux kernel, from which we take the ids. Please clone linux git, and run the getamdgpuids script against it.

**Comment by dr-br** [comment]
The getamdgpuids script did not work properly, I just grepped the amdgpu_drv.c file.

**Comment by clbr** [comment]
Why are there are ton of unrelated r600 id changes?

**Comment by clbr** [comment]
I've just run getamdgpuids against the current linux git and pushed the result. Please try git master.

**Comment by dr-br** [comment]
Commit 15521706464b78dc9af60495b648b9d536b4d085 solved this issue, I think.
Thanks.

**Pull request closed without merging**
