### PR TITLE
Introducing GitHub Actions

### PR DESCRIPTION
**Pull request by danger89**
Build for free 👍🏽

### CODE REVIEW

**Comment by clbr** [comment]
I'm not sure about this, not sure I want to depend on any particular service.

**Comment by danger89** [comment]
It's just GitHub Actions for your pipeline. Currently it only builds it.. No worries. I think it make sense to check if code in pull requests still compiles. And people who want to use the binary without compiling knowledge can grep the binary.

That being said, it's not a hard dependency. I can also introduce a GitLab CI yaml file if you want.

**Comment by danger89** [comment]
You are not depending on GitHub Actions, its just for your convenience. It's up to you if you really want to fully depend on it. In all cases, you are free to merge this PR.

**Comment by clbr** [comment]
Thank you for the PR, but I've decided not to merge this.

**Pull request closed without merging**
