### PR TITLE
Add support for resizeable terminals

### PR DESCRIPTION
**Pull request by ismacasti**
This is a small change to the ui code, that makes it adapt to resized terminals. It just listens to the ncurses signal to update the h, w and hw variables. It also paints the header every time.

Works quite well.

### CODE REVIEW

**Comment by vedranmiletic** [comment]
Tested on Fedora 24 with a Fiji card. Works well.

**Comment by clbr** [comment]
I tested in xterm, rxvt and mrxvt. In the first two it passes, but in mrxvt the VRAM bar gets drawn wrong, one char left to where it should be.

Pic:
Imgur

Now, this may be a mrxvt bug, but I'd appreciate if you looked into this.

**Comment by ismacasti** [comment]
It seems mrxvt prints the cursor when resizing, ignoring ncurses' `curs_set(0)`. It's probably a bug on mrxvt, but anyway, now I set the cursor at 0,0 before refreshing. That will just put a black character square at the beginning of the header. 
image

**Comment by clbr** [comment]
Thanks!

**Pull request merged**
